### ISSUE TITLE
Plotting ideogram

### ISSUE THREAD

**Issue by jemten** [mikaell/chromograph#20]
Hi there
Can't seem to get the ideogram plotting function to work. I try to run the command and when I check the out directory, there are no files there. This is the command I try to run:
```
chromograph --ideo ./hg19_cyto.bed.bed -o ./test/
```
This is the output that I get:
```
outd: ./test/
Plot ideograms with settings
combine:False
outd:./test/
```
Am I doing something obviously wrong here? I have attached the bed file that I tried to use (it's gzipped since github wouldn't let me upload a bed).
cheers,
Anders

[hg19_cyto.bed.gz](https://github.com/mikaell/chromograph/files/4263075/hg19_cyto.bed.gz)

**Comment by mikaell** [comment]
Hi!

Chromograph was expecting the lines to begin with 'chr1' instead of '1'. The fastest/easiest way to fix this is to update the configuration file like this:

```
chromosome_str: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10',
                 '11', '12', '13', '14', '15', '16', '17', '18',
                 '19', '20','21', '22', 'M', 'X', 'Y']
```


However, this does not seem elegant. Do you think Chromograph should try to guess the format?

**Comment by mikaell** [comment]
Pushed a fix that enables both integer (1) and prefix (chr1) formats: `91f0988`. If nothing is parsed an exception will be raised.

**Comment by jemten** [comment]
Thanks!
